### ISSUE TITLE
Dolphin VR killed my Vive controllers

### ISSUE THREAD

**Issue by woodythecrate** [CarlKenner/dolphin#105]
I had no idea it was even possible, but after using DolphinVR my Vive controllers don't connect to the rest of the Vive system. When I push the Vive controller on buttons they beep and turn their lights on, but that's it. 

I went into DolphinVR and changed the controller settings back, but that didn't work.

**Comment by woodythecrate** [comment]
After uninstalling DolphinVR and re-pairing the controllers over and over, they're working again.

**Comment by CarlKenner** [comment]
That's bizarre. That never happened to me.
