### ISSUE TITLE
No image is displayed using OpenVR with DirectX Backend

### ISSUE THREAD

**Issue by penkamaster** [CarlKenner/dolphin#108]
After the "if (g_has_rift)" fix in VRD3D.cpp, it don't crashes anymore, but no image is displayed in the headset.
mirroring you can view the image, including the tracking working and sound, but the headset just shows SteamVR home.

**Comment by CarlKenner** [comment]
I just tested and it works fine for me.

**Comment by CarlKenner** [comment]
Fixed.
