### ISSUE TITLE
New build?

### ISSUE THREAD

**Issue by andybak** [CarlKenner/dolphin#113]
There seems to have been a lot of activity since the last release in July. Is there a plan for a new build or should I knuckle down and figure out how to compile this thing?

**Comment by CarlKenner** [comment]
https://mega.nz/#!tUl0GBKD!KFLwRMj7s0APJkDaj9Kl5oQqDJIVZhH4JkzWCQh74o4

**Comment by andybak** [comment]
Thanks!

**Comment by PapaPlastic** [comment]
Something went wrong. The version in that mega d/L has no head tracking.

**Comment by cercata** [comment]
Is this still alive ?
Or the DEV got Hired by Nintendo? xD

**Comment by CarlKenner** [comment]
Assuming @PapaPlastic was using SteamVR, that issue is now fixed.
I also brought Dolphin VR features up to Dolphin master for then end of January 2017 (last year), which should solve @andybak's issue too.
Fixed in the next version.
Yes, I'm still alive. No, I didn't get hired by Nintendo.
