### ISSUE TITLE
Just tried the new build from 5 days ago and head tracking is no longer working.

### ISSUE THREAD

**Issue by theman0864** [CarlKenner/dolphin#114]
Im using gear vr version of riftcat on a galaxy s7 and the 5.250 build from June works fine with head tracking. I just tried the new build and the image stays static. Im running an I5 2500k and gtx 1060. I have it set to direct x 11. I cant find any settings in the vr tabs to adjust head tracking or turn it on and off but I think I might be missing something. I really love what you guys have done with dolphin VR btw!

**Comment by CarlKenner** [comment]
Hmmm... I don't have an S7, and I've never tried riftcat, but maybe I can test it on my friend's GearVR.

It might be because this is built with a later version of the Oculus SDK. I can try rebuilding it with an earlier SDK version.

**Comment by theman0864** [comment]
Thanks for getting back with me on this! That might be it I think Riftcat uses the the 0.6 to 0.8 sdk and some newer oculus games work with revive through Steam.

**Comment by theman0864** [comment]
I found a fix! Someone made a steam vr exe and using this seems to work!
https://drive.google.com/file/d/0Bxp6jH7WYzk-a3FzbWJIa3JEYTg/view
