### ISSUE TITLE
Just wanted to say thank you for all of your work.

### ISSUE THREAD

**Issue by theman0864** [CarlKenner/dolphin#118]
I really just wanted to say thanks for all of your work. I have recently been playing your doom 3 VR mod. It really amazes me how well polished this is. Definitely one of the best experiences in VR to date. I have also had a lot of fun with your dolphin VR branch and I plan to try your psp VR branch sometime soon too. I was curious if you were working on anything else in VR did a little research and realized that you created glove pie. I played around with this several years ago and used my wiimote as a mouse for a while. You do amazing stuff!

Thanks

theman0864

**Comment by CarlKenner** [comment]
Thank you very much! You are too kind.
Sorry I had been slacking off and hadn't done anything on any of those projects since April. I'm trying to get back into working on them again.
