### ISSUE TITLE
Discussion on Main Branch Hotkeys Issues

### ISSUE THREAD

**Issue by cegli** [CarlKenner/dolphin#26]
Hey, I was wondering what you wanted to do about the main branch hotkeys situation.  I've looked at the code, and it currently polls the keyboard and any attached device for every single possible hotkey, and then does that every frame.  It really drags down performance, plus lots of other stuff seems broken.

Should I just revert that commit for now and wait for the main branch to fix it?  I could work on fixing it, but it really requires a pretty serious rearchitecture.  I'd rather spend my time on other things.  What are your thoughts?

**Comment by CarlKenner** [comment]
I guess we just have to revert it for now. I can't even test games or set their scale properly with the keyboard hotkeys not working.

**Comment by cegli** [comment]
Yeah, not ideal...  I'm not sure how this one made it into the Master in its current state.

**Comment by cegli** [comment]
Okay, I just added an option to switch back and forth between the new and old hotkeys with a define in frame.h.  I figured this system will make it easy to remove the old hotkeys code once it's no longer needed, and test the fixes that the main branch will eventually make.  I think this can be closed.
