### ISSUE TITLE
Real WiiMote Losses Connection/ Nunchuk Calibration

### ISSUE THREAD

**Issue by Sylux102** [CarlKenner/dolphin#44]
I've noticed (particularly when playing Metroid Prime Trilogy PAL) that the Wiimote will sometimes lose connection, or when the nunchuk is plugged in, all values on one axis are read as all positive or all negative values (ie, a regular joystick usually goes -1 to 0 to 1, whereas this rev of Dolphin VR (4.0 9170) has the joystick to 1 to 0 to 1, causing the player to only move in one direction) but only occasionally. Not all the time.

Unplugging/replugging the nunchuk sometimes fixes this, but when it does fix it sometimes the IR pointer will stop functioning. All the buttons work correctly, but it seems there is bad handling of the axes for both the nunchuk attachment and the IR pointer.

It also seems there's a memory leak somewhere, since performance gets really choppy over time (which isn't related to the issue, but in case you weren't aware).

**Comment by Sylux102** [comment]
Can't edit my issue, but I'll add for info:

Issue is not the wiimote/nunchuk.

Tested with multiple motes/chuks, all caused the issue.

**Comment by CarlKenner** [comment]
Does the issue also occur in the latest non-VR Dolphin?

**Comment by Sylux102** [comment]
No, this issue is only present in the VR builds of Dolphin.

**Comment by CarlKenner** [comment]
I can reproduce this bug. No idea what's causing it though. My real wiimote code looks identical to the main branch.

**Comment by CarlKenner** [comment]
Finally fixed (in the next version). Sorry it took so long.
