### ISSUE TITLE
Source file scmrev.h missing?

### ISSUE THREAD

**Issue by Ironsight** [CarlKenner/dolphin#45]
![image](https://cloud.githubusercontent.com/assets/4589139/15200970/8dce08ae-17b1-11e6-9486-a40303434176.png)

**Comment by CarlKenner** [comment]
It's automatically created (by makescmrevgen.h.js) when building, but you need to have Git installed for it to work.
If you really can't get it to work, here's the contents of my Source\Core\Common\scmrev.h:

#define SCM_REV_STR "3c72ea89f9ef49588d3fc0124f9c02138a9b0bba"
#define SCM_DESC_STR "4.0-9522-dirty"
#define SCM_BRANCH_STR "VR-Hydra"
#define SCM_IS_MASTER 0

**Comment by CarlKenner** [comment]
Did you get it working yet?
