### ISSUE TITLE
Direct3D 12 support

### ISSUE THREAD

**Issue by CarlKenner** [CarlKenner/dolphin#47]
Direct3D 12 is not supported yet, but should be one day.

**Comment by Helios747** [comment]
btw, nobody watches the issue tracker here.

https://bugs.dolphin-emu.org

Also, we do have D3D12 support. Go download a development build?

**Comment by JosJuice** [comment]
@Helios747 Have you considered that this could be the issue tracker for this fork and that D3D12 maybe isn't supported here?
