### ISSUE TITLE
Vive Controller "RDPadRight" is listed twice

### ISSUE THREAD

**Issue by DanTycoon** [CarlKenner/dolphin#53]
On the controls for Vive controllers, the control "RDpadRight" is listed twice.

Issue can be seen/fixed here:
https://github.com/CarlKenner/dolphin/blob/VR-Hydra/Source/Core/InputCommon/ControllerInterface/Vive/ViveInput.cpp#L40

**Comment by CarlKenner** [comment]
Fixed. Thanks.

I didn't notice this because the actual HTC Vive doesn't have a DPad. But SteamVR lists those buttons for controllers that do have a DPad, so I include them in the list just in case someone is using SteamVR with a different type of controller.

**Comment by DanTycoon** [comment]
I was just scrolling through the entries and noticed this one appeared twice.

Thanks for the work!
